import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { Vortex } from "react-loader-spinner";
import axios from "axios";
import useMarket from "../web3/hooks/useMarketPlace";
import { Contract, ethers } from "ethers";
import useNFT from "../web3/hooks/useNft";
import { shortenAddress } from "../utils/helper";

const Home: NextPage = () => {
  const [nft, setNft] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  let pre = "https://dweb.link/ipfs/";
  // let a = "ipfs://bafybeib4i6eqetvke4br2to4eepu3msat5wt46xdngvikkocyy6k6aukra/ChainedThrift.jpg"
  // const output = a.replace("ipfs://", pre)
  // console.log(output)
  // const fetchData =  async() =>{
  //   const response = await axios.get("https://bafyreifpt4d3fleqj6uz7m5gx46e5hsuwopcy52qu6l56iqgubudtpsua4.ipfs.dweb.link/metadata.json")
  //   if(response.status === 200){
  //     console.log(response.data)
  //   }
  //   console.log(response)
  // }

  const { market } = useMarket();
  const { contract } = useNFT();

  const fetchNFTs = async () => {
    setLoading(true);
    try {
      const datas = await market.fetchMarketItems();
      const items: any = await Promise.all(
        datas.map(async (data: any) => {
          let tokenURI = await contract.tokenURI(data.tokenId);
          let formatURI = await tokenURI.replace("ipfs://", pre);
          let meta = await axios.get(formatURI);
          let price = ethers.utils.formatUnits(data.price.toString(), "ether");
          let formatImage = await meta.data.image.replace("ipfs://", pre);
          let item = {
            price,
            tokenId: data.tokenId.toNumber(),
            seller: data.seller,
            owner: data.owner,
            image: formatImage,
            description: meta.data.description,
          };
          return item;
        })
      );
      setNft(items);
      setLoading(false);
    } catch (error) {
      console.error(error);
    }
  };

  const buyNFT = async (nft: any) => {
    const price = ethers.utils.parseUnits(nft.price.toString(), "ether");
    console.log(price);
    const transaction = await market.buyAsset(nft.tokenId, {
      value: price,
    });
    await transaction.wait();
    fetchNFTs();
  };

  useEffect(() => {
    fetchNFTs();
  }, []);

  if (!loading && !nft.length) return <p>No Item in the MarketPlace</p>;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto p-2">
        {loading ? (
          <div className="flex justify-center mt-12">
            <Vortex
              visible={true}
              height="80"
              width="80"
              ariaLabel="vortex-loading"
              wrapperStyle={{}}
              wrapperClass="vortex-wrapper"
              colors={["red", "green", "blue", "yellow", "orange", "purple"]}
            />
          </div>
        ) : (
          <div className="grid grid-cols-4 gap-4 ">
            {nft.map((item, idx) => {
              return (
                <div className="border-2 rounded-lg border-purple-500 p-2">
                  <div className="mb-1">
                    <img src={item.image} alt="image" />
                  </div>
                  <p>
                    <span className="mr-2">Seller:</span>
                    {shortenAddress(item.seller)}
                  </p>
                  <p>
                    <span className="mr-2">Description:</span>
                    {item.description}
                  </p>
                  <p>
                    <span className="mr-2">Price:</span>
                    {`${item.price} ETH`}
                  </p>
                  <button
                    onClick={() => buyNFT(nft)}
                    className="bg-purple-500 outline-none  rounded-sm text-white w-full"
                  >
                    Buy NFT
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </section>
    </div>
  );
};

export default Home;
